/*
**********************SPI in polling method
 * Atmega32_SPI_Slave.c
 *
 * Created: 5/6/2012 9:00:21 PM
 *  Author: BB
 */ 
#define F_CPU 16000000UL
#include <avr/io.h>
#include <util/delay.h>

#define SS 4
#define MOSI 5
#define MISO 6
#define SCK 7
void SPI_slave_init()
{
	DDRB = (0 << MOSI)|(1 << MISO)|(0 << SCK)|(0 << SS);
	SPCR = (1 << SPE)|(0<<MSTR); // Set as Slave & polling
}

int main(void)
{
	DDRA = 0xFF;
	char val = 255;
	SPI_slave_init();
    while(1)
    {
        SPDR = val;
		while(!(SPSR & (1 << SPIF)));
		PORTA = SPDR;
		val--;
		_delay_ms(400); // will also work if not given because the spi clock is generated by master
    }
	return 0;
}